services:
  - type: web
    name: the-game-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production